### ISSUE TITLE
Project feedback

### ISSUE THREAD

**Issue by adamstep** [eli-stewart/Instawork#1]
Hi @eli-stewart , I followed the instructions in the README but getting this frontend error:

```
Module not found: Can't resolve 'axios'
> 1 | import axios from 'axios';
    | ^
  2 |
  3 | const apiClient = axios.create({
  4 |   baseURL: ['http://localhost:8000/api'](http://localhost:8000/api), 

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./src/app/page.tsx
```

**Comment by eli-stewart** [comment]
Apologies for not including axios in my package.json. It should run properly now! @adamstep

**Comment by adamstep** [comment]
It seems like there might be some other libs missing?

<img width="1199" alt="Screenshot 2024-09-18 at 2 59 01 PM" src="https://github.com/user-attachments/assets/d0603b64-23cd-4de3-ae41-724b603cf552">

**Comment by eli-stewart** [comment]
My bad on that. Thanks for your patience. It should be good to go now @adamstep

**Comment by adamstep** [comment]
Thanks, got it running now, looks good!

**Comment by eli-stewart** [comment]
Hey @adamstep I'm glad you got it up and running. I hope you're happy with the quality of my code!

Please let me know if there are any improvements, adjustments or additions you'd like to see implemented
